apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k002-hom-nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client