apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name: pod-1
      labels:
        tier: backend
    spec:
      containers:
      - name: pod-1-container
        image: nginx