apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: teste-nfs