apiVersion: v1
kind: Pod
metadata:
  name: k001-prod-nginx-pod
  labels:
    app: k001-prod-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html

  volumes:
    - name: nginx-data
      persistentVolumeClaim:
        claimName: k001-prod-nginx-pvc